site_name: れいとの軌跡

theme:
  name: material
  features:
    - navigation.indexes
  language: ja

plugins:
  - search
  - blog:
      archive_date_format: yyyy年MM月
      archive_url_date_format: yyyy/MM
      
extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list

nav:
  - ホーム: index.md

  - ブログ:
    - blog/index.md

  - 作品:
      - 作品って？: works/index.md

  - 知見:
      - 未分類:
        - Github Ppages + MkDocsでサイト構築: knowledge/other/create_site_with_github_pages_and_mkdocs.md
      - Tips:
        - MkDocs: knowledge/tips/mkdocs.md