name: Preview Test Workflow

on:
  push:
    branches:
      - "preview/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout preview branch
        uses: actions/checkout@v6
        with:
          path: preview

      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          ref: main
          path: main

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # preview/xxxx → xxxx を取り出す
      - name: Get preview ID
        id: preview
        shell: bash
        run: |
          PREVIEW_ID="${GITHUB_REF_NAME#preview/}"
          echo "id=$PREVIEW_ID" >> "$GITHUB_OUTPUT"
          echo "Preview ID: $PREVIEW_ID"

      - name: Build main site
        working-directory: main
        run: mkdocs build -d ../deploy

      - name: Build preview site
        working-directory: preview
        run: mkdocs build -d "../deploy/_preview/${{ steps.preview.outputs.id }}"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4